basePath: /
definitions:
  router.HealthResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API boilerplate em Golang utilizando Fiber, GORM e PostgreSQL
  title: Boilerplate Golang API
  version: v1.0.1
paths:
  /api/health:
    get:
      description: Endpoint para validar se a API esta em execucao
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.HealthResponse'
      summary: Verifica saude da API
      tags:
      - Health
swagger: "2.0"
